sylius_resource:
    resources:
        app.editor:
            driver: doctrine/orm
            classes:
                model: App\Entity\Editor\Editor
                form: App\Form\Type\EditorType
                interface: App\Entity\Editor\EditorInterface
