imports:
    - { resource: "resources.yaml" }

services:
    sylius.fixture.nintendo_product:
        autowire: false
        class: App\Fixture\NintendoProductFixture
        arguments:
            - "@sylius.fixture.product"
        tags: ['sylius_fixtures.fixture']

    App\Form\Type\EditorType:
        arguments:
            - '%app.model.editor.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: App\Form\Type\EditorType }

    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    app.form.extension.type.product:
        class: App\Form\Extension\ProductTypeExtension
        arguments:
            - "%sylius.model.product.class%"
            - "%sylius.form.type.product.validation_groups%"
            - "@sylius.product_variant_resolver.default"
            - "@sylius.factory.product_attribute_value"
            - "@sylius.translation_locale_provider"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }

    App\Fixture\Factory\EditorExampleFactory:
        arguments:
            - '@app.factory.editor'

    App\Fixture\EditorFixture:
        arguments:
            - '@app.manager.editor'
            - '@App\Fixture\Factory\EditorExampleFactory'
        tags:
            - { name: sylius_fixtures.fixture }
