imports:
    - { resource: "resources.yaml" }

services:
    sylius.fixture.nintendo_product:
        autowire: false
        class: App\Fixture\NintendoProductFixture
        arguments:
            - "@sylius.fixture.product"
        tags: ['sylius_fixtures.fixture']

    App\Form\Type\EditorType:
        arguments:
            - '%app.model.editor.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: App\Form\Type\EditorType }

    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
