imports:
    - { resource: "fixtures.yaml" }

winzou_state_machine:
    app_editor:
        class: "%app.model.editor.class%"
        property_path: status
        graph: app_editor
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            approved: ~
        transitions:
            approve:
                from: ['new'] # Can be many
                to: 'approved' # Always one of course
        callbacks:
            after:
                app_editor_approved:
                    on: ["approve"]
                    do: ["@app.email_manager.editor_approved_manager", "sendEmail"]
                    args: ["object"]

sylius_mailer:
    emails:
        editor_approved:
            subject: 'Editor approved'
            template: 'Email/editorApproved.html.twig'
