app_admin_editor:
    resource: |
        alias: app.editor
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_admin_editor
        vars:
            all:
                subheader: app.ui.editor
            index:
                icon: 'id badge outline'
    type: sylius.resource

app_admin_editor_approve:
    path: admin/editor/{id}/approve
    methods: ['PUT']
    defaults:
        _controller: app.controller.editor:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_editor
                transition: approve
            redirect: referer
