app_admin_editor:
    resource: |
        alias: app.editor
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_admin_editor
        vars:
            all:
                subheader: app.ui.editor
            index:
                icon: 'id badge outline'
    type: sylius.resource
